pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Huma Gel
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://www.humagel.com
#
# 2. URL of this page
url:              http://theeimac.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           Huma Gel
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://igg.me/at/humagel
  #
  # URL of a cover photo of your project
  cover_image:    http://www.humagel.com/wp-content/uploads/2013/07/Huma-Runner-Girl-crop.jpg
  #
  # Use a one-liner to describe your project
  description:    All-natural, great tasting energy gel
#
# 4. Your Twitter handle
twitter_handle:   HumaGel
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  This is Huma Gel greeting you from Nashville. <br />
  Here's to tell you that our project is now live on Kickstarter,
  and now we have to count on your support to not only back the project, but also share the love. ♥
